;THOMAS JOSHUA R. CORONEL
;SEPTEMBER 13, 2025
TITLE prog14.asm
DOSSEG
.MODEL SMALL
.STACK 0100H
.DATA
    STR1 DB "ARELLANO$"
.CODE
    MOV AX, @DATA
    MOV DS, AX
    MOV ES, AX      ;FOR STRING DISPLAY

    MOV AX, 0600H
    MOV BH, 07H         ;CLEAR SCREEN
    MOV CX, 0000H
    MOV DX, 184FH
    INT 10H

    MOV AH, 13H         ;REQ FOR CHAR W ATTRIBUTES
    MOV AL, 00H         ;DO NOT ADV CURSOR
    MOV BH, 00H         ;PAGE NUM 0
    MOV BL, 94H         ;1 BLUE 4 RED PERO BLINKING SO PLUS 8 SA BLUE
    
    MOV BP, OFFSET STR1
    MOV CX, 0008H
    MOV DH, 0CH ;ROW 12
    MOV DL, 21H ;COL 36
    INT 10H

    MOV AX, 4C00H
    INT 21H
END